server:
    port: 8081

spring:
    datasource:
      url: jdbc:h2:mem:testdb
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: true
kafka:
    bootstrapServers: localhost:9092
    concurrency: 2
    maxBatchSize: 5
    topic: 'kishore.topic'
    group: 'kishore.group'
